language: java
jdk:
  - openjdk11
#services:
#  - mongodb
# does not allow to specify MongoDB version, so instally it explicitly see https://github.com/mongodb/pymodm/blob/master/.travis.yml https://docs.travis-ci.com/user/languages/java/

env:
  matrix:
    - MONGODB=4.0.6 # no newer (4.2.3) using fastdl, else switch to apt install

matrix:
  fast_finish: true

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork

#script:
#  - mvn test -B

after_script:
- pkill mongod
