package org.oasis.datacore.sample.converter;

import org.springframework.data.annotation.Id;

/**
 * To test embedded / subelements and how mongo lifecycle events pan out with them
 * 
 * @author mdutoo
 *
 */
public class Comment {

   /** NO since Comment is embedded, no @Id is generated by spring data !!! */
   @Id
   private String id;
   private String user;
   private String text;
   public String getId() {
      return id;
   }
   public void setId(String id) {
      this.id = id;
   }
   public String getUser() {
      return user;
   }
   public void setUser(String user) {
      this.user = user;
   }
   public String getText() {
      return text;
   }
   public void setText(String text) {
      this.text = text;
   }
}
