#! /bin/sh
### BEGIN INIT INFO
# Provides:          tomcat7-dc
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tomcat7-dc initscript
# Description:       Tomcat 7 Datacore script for SysV init. Requires : sudo, nohup, bash.
### END INIT INFO

# Author: Openwide <contact@openwide.fr>
#

# package conf
INSTALL_PATH=/home/axxx/install
TOMCAT_NAME="tomcat7-dc"
TOMCAT_INSTALL_PATH=$INSTALL_PATH/$TOMCAT_NAME
SCRIPTNAME=tomcat7-dc

case "$1" in
  start)
        PWD=`pwd`
        cd $TOMCAT_INSTALL_PATH
        sudo -u axxx nohup bash -c "./bin/catalina.sh run" 1>>/var/log/$SCRIPTNAME.log 2>> /var/log/$SCRIPTNAME.err.log &
        cd $PWD
        ;;
  stop)
        PWD=`pwd`
        cd $TOMCAT_INSTALL_PATH
        sudo -u axxx bash -c "./bin/catalina.sh stop"
        cd $PWD
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
        exit 3
        ;;
esac
